### DISCUSSION TITLE
Identifying  pods running on a node

### DISCUSSION THREAD

**Discussion by davem-git** [kubemod/kubemod#111] [Q&A] [answered]
I want to create a rule to check if a specific daemonset is running on a node. If it's not there, I want to taint the node. If it's there, I. want it to do nothing. Is that possible? I don't see any examples of using nodes to get pods.

**Comment by vassilvk** [comment]
I'm not sure this is something one would do with a mutating admission controller.
Mutating controllers can only mutate resource manifests as they are created/updated through K8S API server calls.

Also, I'm not sure I understand the timing of what you want to accomplish. The pods of a DaemonSet are scheduled on a node asynchronously and after the node is added to the cluster. There is a gap in time where a node is alive, but the pods of a DaemonSet are not scheduled on it yet. If you check at that point, you may decide to taint the node, because the DaemonSet pods are not scheduled there yet, but if you check a second later, you may decide to not taint the node as the pod may be scheduled.
So there seems to be a race condition here.

**Reply by davem-git** [reply]
I want to prevent anything from being scheduled on the node until the pod from the daemonset is working.

> There is a gap in time where a node is alive, but the pods of a DaemonSet are not scheduled on it yet. If you check at that point,
That's fine, the daemonset will remove the taint afterwords and allow other pods to be scheduled. 

I did this, which works when new nodes get added. It doesn't work when an existing node gets patched. As it comes up the second time it already has the label, and therefore doesn't apply the taint. 

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: add-cilium-taint
  namespace: kubemod-system
spec:
  type: Patch
  executionTier: 0
  match:
    - select: '$.kind'
      matchValue: Node
    - select: '$.metadata.labels["kube-moderule-cilium-applied"]'
      negate: true
  patch:
    - op: add
      path: /metadata/labels/kube-moderule-cilium-applied
    - op: add
      path: /spec/taints/-1
      value: |-
        effect: NoSchedule
        key: node.cilium.io/agent-not-ready
        value: "true"

```

**Reply by vassilvk** [reply]
I’m not sure I understand the part about patching existing nodes. If the label is there, why is the taint missing? If it’s missing because the daemonset removed it, then I’m not sure why do you need to add the taint back.

**Reply by davem-git** [reply]
It's missing the taint because the daemonset removed it. Which is expected. When a node restarts in the ideal world, the taint would be re-added, and the daemonset would remove it when it's ready. 

Otherwise, it's possible for a pod to stand up before cilium, and that pod will need a restart after to fix it.

**Reply by vassilvk** [reply]
So ultimately, what you need is a way to check if the daemonset pod is there at the time the ModRule is evaluated.
This is currently not possible, but I see a way to do it through KubeMod's synthetic refs.
Currently KubeMod injects [synthetic references](https://github.com/kubemod/kubemod#synthetic-references) for `namespace` (for all namespaced objects) and `node` (for `pod` objects). If a new `pods` synthetic ref is injected for `node` objects, then you should be able to put together a ModRule to do the patch you need only based on the presence (or lack of) the cilium pod, without resorting to marker labels such as kube-moderule-cilium-applied.
Please let me know if this would resolve your issue.

**Reply by davem-git** [reply]
oh ok, thanks I'll work on this later today.  trying to wrap my head around it. If I understand this correctly It should look something like this?

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: add-cilium-taint
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - UPDATE

  match:
    - select: "$.kind"
      matchValue: "node"
    - select: "$.syntheticRefs.pod.metadata.labels"
      matchValue: k8s-app=cilium
      negate: true
  patch:
    - op: add
      path: /spec/taints/-1
      value: |-
        effect: NoSchedule
        key: node.cilium.io/agent-not-ready
        value: "true"

```

**Comment by vassilvk** [comment]
If we go for injecting pod manifests in node objects as synthetic refs, those would be injected as an array called `pods`, so the match select would be something like:
```
match:
...
    - select: '$.syntheticRefs.pods[*].metadata.labels["k8s-app"]'
      matchValue: cilium
      negate: true
```

That said, I am having second thoughts about this approach. Pulling in pod manifests into each node on CREATE/UPDATE may prove to be expensive. It may be a much better approach to pull in the node's `status` sub-resource as a means to get information about the node's pods and state at the time of the UPDATE operation.
