### DISCUSSION TITLE
kind: Namespace

### DISCUSSION THREAD

**Discussion by llamashoes** [kubemod/kubemod#40] [Q&A] [answered]
kubemod is super useful so far, but I have a potential use case where I would like to manage `istio.io/rev` labels on each namespace using kubemod (vs having to update each individually). 
I have tried the following match and have been unable to get the operator to seem to see anything:

```
  match:
    - select: '$.kind'
      matchValue: 'Namespace'

    - select: '$.metadata.name'
      matchValue: 'bravo2'
```

First question would be would this even work? I have tried putting the rule in a specific namespace and then updated the namespace and haven't been able to get the operator to seem to see the namespace kind. The same test works great on deployments etc (per namespace). 

So thats my question. I haven't dug into the code too much and thought I would throw this out before doing so. Thanks
