### DISCUSSION TITLE
Use wildcards when removing `paths`?

### DISCUSSION THREAD

**Discussion by renzedj** [kubemod/kubemod#90] [Q&A]
Am I able to use a wildcard when removing a path from a pod? E.g., if I need to remove all annotations starting with `com.example.*`, will the following work?

```yaml
patch:
  - op: 'remove'
    path: '/metadata/annotations/com.example.*'
```

**Comment by vassilvk** [comment]
Hi @drenze-athene,

In KubeMod performing the same `patch` operation against a set of elements is done with a combination of the `select` JSONPath expression and `#` placeholders in the `path` section. Unfortunately the JSONPath spec does not allow for wildcard (or regex) key targeting.

That said, in a future version of KubeMod, I should be able to extend KubeMod's JSONPath with a custom `key` filter function which would allow for filtering based on key name using both equality and regex match operators.

Here's what I'm thinking:

```yaml
patch:
  - op: remove
    select: '$.metadata.annotations[? key(@) =~ "com\.example\..*"]'
    path: '/metadata/annotations/#0'
```

Thoughts?
