### ISSUE TITLE
Support ModRules based on the operation type

### ISSUE THREAD

**Issue by orbatschow** [kubemod/kubemod#103]
At the moment kubemod does not differentiate between the admissions request operation type.

It would be great to have a feature, that allows the user to apply ModRules only to certain admission requests, e.g. "DELETE".

With this feature implemented one could utilize ModRules like the one below:

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: reject-namespace-deletion
  namespace: kubemod-system
spec:
  type: Reject
  operation:
    - DELETE

  rejectMessage: 'deletion of protected namespaces is not allowed'

  match:
    - select: '$.kind'
      matchValue: 'Namespace'

    - select: '$.metadata.labels.protected =~ "yes"'

```
