### ISSUE TITLE
Document  ref.kubemod.io/inject-node-ref  rule

### ISSUE THREAD

**Issue by runningman84** [kubemod/kubemod#113]
In your docs you describe this "If you want to have this rule apply to pods which don't have this annotation, you can create another ModRule which injects ref.kubemod.io/inject-node-ref into any pod that matches a given criteria, or to all pods that are created in the cluster."

Unfortunately it is quite difficult to implement that, my lastest failing rule looks like this:
`````

---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-node-ref-annotation
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - CREATE
    - UPDATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'

    - select: '$.metadata.annotations["ref.kubemod.io/inject-node-ref"]'
      matchValue: "true"
      negate: true

  patch:
    # Add annotations ref.kubemod.io/inject-node-ref
    - op: add
      path: /metadata/annotations/ref.kubemod.io~1inject-node-ref
      value: "true"
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-topology-labels
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - UPDATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'
    # ...which have access to the node's manifest through the synthetic ref injected by KubeMod.
    - select: '$.syntheticRefs.node.metadata.labels'

  patch:
    # Grab the node's region and zone and put them in the pod's corresponding labels.
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1region
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/region"}}"'
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1zone
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/zone"}}"'

`````

It would be great to have a working example in the docs.

Once I had the rule in place I could not spin up any new pod:

`````
│ {"level":"info","ts":"2023-01-26 16:42:59.963Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"f59ff87d-3143-4f7b-a9d3-8e65351d6df9","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:05.121Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"eac8adc6-2cc0-4207-8264-6e8f8c44d47f","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:15.388Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"95182d7e-5d88-4142-a75f-d071fd1c1b73","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:25.383Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"ccfdc133-bf8b-4a1a-b6b0-9625beab68d7","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:25.408Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"508b45db-4c46-4b36-800f-6c4051a78e67","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:25.585Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"1d65cd07-51c2-4567-91a3-281dc934d107","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:43:35.894Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"50a132d7-1aa5-4692-a3e4-be75c75cc1ff","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:45:00.287Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"4d6adbb6-bc32-4d39-88db-081c2d6201f2","namespace":"wp-multisite-demo","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}                  ││││││
│ {"level":"info","ts":"2023-01-26 16:45:00.387Z","logger":"dragnet-webhook","msg":"Applying ModRule patch","request uid":"6b4cdc1b-3de1-4831-af27-6990a664f2e2","namespace":"wp-bedrock-sample","resource":"pods/","operation":"CREATE","patch":[{"op":"add","path":"/metadata/annotations/ref.kubemod.io~1inject-node-ref","value":true}]}    
`````

**Comment by vassilvk** [comment]
Hi @runningman84,

Right - it would be best to document this.
The issue with the last version of your ModRules is that inject-node-ref-annotation ModRule attempts to inject annotation `ref.kubemod.io/inject-node-ref` with boolean value `true`, instead of with string `"true"`.

Try this:

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-node-ref-annotation
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - CREATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'

    - select: '$.metadata.annotations["ref.kubemod.io/inject-node-ref"]'
      matchValue: 'true'
      negate: true

  patch:
    # Add annotations ref.kubemod.io/inject-node-ref
    - op: add
      path: /metadata/annotations/ref.kubemod.io~1inject-node-ref
      value: '"true"'
```

Two things to note:
- The last line sets the value to `'"true"'` instead of `'true'`. I know, this is not intuitive, but with a ModRule you are putting together a JSON patch, so you are allowed different types of values. The reason this ModRule rendered your cluster incapable of creating pods is that the patch with the boolean value of `true` ended up producing an invalid Pod manifest, which prompted the Kubernetes API server to keep retrying the KubeMod webhook. KubeMod itself is unaware of the issue, so it keeps patching and returning the patched (invalid) pod.
- I changed the ModRule to apply only when Pods are created (see `admissionOperations`). You don't really need to reapply this annotation on every subsequent UPDATE.

**Comment by vassilvk** [comment]
@runningman84, documentation updated with a sample ModRule which injects `ref.kubemod.io/inject-node-ref`.

**Comment by runningman84** [comment]
Thanks for your quick help, the labels now work as designed...

A common use case would be to add the AWS_ZONE as an env variable. I tried it this way:
`````
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-topology-env
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - UPDATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'
    # ...which have access to the node's manifest through the synthetic ref injected by KubeMod.
    - select: '$.syntheticRefs.node.metadata.labels'

    - select: '$.spec.template.spec.containers[*].env[? @.name == "AWS_ZONE" ]'
      negate: true

  patch:
    # Grab the node's zone and put them in the pod's env.
    - op: add
      select: '$.spec.template.spec.containers[? @.name =~ "wordpress-bedrock-php-fpm" ]'
      path: /spec/template/spec/containers/#0/env/-
      value: |-
        name: AWS_ZONE
        value: {{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/zone"}}
``````


Unfortunately the wordpress pods do not get the expected env in the php-fpm container section.

**Comment by vassilvk** [comment]
The reason this ModRule won't work is that it attempts to add a new environment variable to a container's spec during an UPDATE operation. This part of the Pod spec is immutable. You can only change it with a ModRule on CREATE.

In order to inject topology into the containers as environment variables, you should use a combination of KubeMod rules to copy node topology labels into pod labels, and then Kubernetes Downward API to grab the values from the pod labels and inject them as environment variables.

Here's the full list of resources:

### ModRule to inject `ref.kubemod.io/inject-node-ref` into every pod

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: patch-pod-with-inject-node-ref
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - CREATE

  match:
    - select: '$.kind'
      matchValue: 'Pod'
    - select: '$.metadata.annotations["ref.kubemod.io/inject-node-ref"]'
      matchValue: 'true'
      negate: true

  patch:
    - op: add
      path: /metadata/annotations/ref.kubemod.io~1inject-node-ref
      value: '"true"'
```

### ModRule to copy node topology labels into pod topology labels

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-topology-labels
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - UPDATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'
    # ...which have access to the node's manifest through the synthetic ref injected by KubeMod.
    - select: '$.syntheticRefs.node.metadata.labels'

  patch:
    # Grab the node's region and zone and put them in the pod's corresponding labels.
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1region
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/region"}}"'
    - op: add
      path: /metadata/labels/topology.kubernetes.io~1zone
      value: '"{{ index .Target.syntheticRefs.node.metadata.labels "topology.kubernetes.io/zone"}}"'
```

### ModRule to create environment variable which pulls zone from pod's zone topology label

```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: inject-topology-variables
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: ".*"
  admissionOperations:
    - CREATE

  match:
    # Match pods...
    - select: '$.kind'
      matchValue: 'Pod'
    # ...which have a wordpress container with no AWS_ZONE variable.
    - select: '$.spec.template.spec.containers[? @.name =~ "wordpress-bedrock-php-fpm" ]'
    - select: '$.spec.template.spec.containers[*].env[? @.name == "AWS_ZONE" ]'
      negate: true

  patch:
    # Construct a K8S Downward API ref environment variable to grab the zone from the label
    # injected by by ModRule inject-topology-labels.
    - op: add
      select: '$.spec.template.spec.containers[? @.name =~ "wordpress-bedrock-php-fpm" ]'
      path: /spec/template/spec/containers/#0/env/-1
      value: |-
        name: AWS_ZONE
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['topology.kubernetes.io/zone']
```
