### ISSUE TITLE
Add ability to construct patches based on select expression

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod#12]
Currently the `path` of a patch operation is a simple full path to the target element of the patch (as per [JSON Patch RFC 6902](https://tools.ietf.org/html/rfc6902)).

This works for some cases, however, there is a whole category of cases where the user doesn't know the exact location of the item which needs patching. For example, when the user needs to patch a container of a pod based on the container name. Today the user is forced to use a container index hard-coded in the `path` of the patch operation. This is obviously fragile as the ModRule depends on the container always being positioned at that index.

To solve this issue, introduce a `select` JSON Path filter expression similar to the one used in the `select` field of the `match` section. The JSON Path expression is evaluated against the target object and a patch operation is constructed for each result of the select query.

Each result of the query is also tagged with a composite key which contains the index values of all the wildcards (such as `containers[*].ports` and `$containers..ports`) and filters (such as `containers[? @.name == "container-xyz"]`) present in the select.

For example, the following expression produces a two-part composite key:
`$.spec.containers[*].ports[?@.containerPort == 80]`

The first part of the key is the index of the `containers` and the second one is the index for the `ports`.

When constructing the `path` of the patch, one can use placeholders `#i` to access the different parts of the composite key. For the above example, `#0` is the placeholder for the `containers` index and `#1` is the placeholder for the `ports` index.

The following example only uses the index of the containers in order to patch the securityContext of every container in a pod with port 80.

```yaml
- op: add
      select: '$.spec.containers[*].ports[?@.containerPort == 80]'
      path: '/spec/template/spec/containers/#0/securityContext'
      value: |-
        fsGroup: 101
        runAsGroup: 101
        runAsUser: 101
        runAsNonRoot: true
```
