### ISSUE TITLE
Introduce matchFor

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod#25]
Currently when `matchValue`, `matchValues` or `matchRegex` is used for a match criteria item, the results of `select` are matched against the `match...` requirement and if **any** of the results has a match, the match criteria is considered a positive match.

There exist a number of use cases where we need to have a positive match only when **all** of the results from `select` match the `match...` requirement.

To resolve this, introduce a new optional enum criteria item field -- `matchFor`.
It can be either `All` or `Any`.
It defaults to `Any`.

For example:
```yaml
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: reject-malicious-external-ip-services
spec:
  type: Reject

  match:
    - select: '$.kind'
      matchValue: 'Service'

    # Allow only IPs in subnet 123.4.5.*
    - select: '$.spec.externalIPs[*]'
      matchFor: All
      matchRegex: '123\.4\.5\.*'
      negate: true
```
