### ISSUE TITLE
Limit the default set of target resources

### ISSUE THREAD

**Issue by vassilvk** [kubemod/kubemod#43]
Currently KubeMod throws a wide net when targeting Kubernetes resources.
This may lead to multi-node cluster instability when the host running KubeMod is restarted because the API server passes **all** objects through KubeMod, including low-level objects such as events, leases and endpoints.
When KubeMod is down, the API server starts stuttering and in some severe cases it may even restart.

To avoid all this, deploy KubeMod with an initial set of target resources:
```
namespaces
configmaps
persistentvolumeclaims
secrets
services
daemonsets
deployments
statefulsets
cronjobs
jobs
```

Document how to modify the KubeMod configuration post-install to target a wider set of resources:

1. Create a patch file `patch.yaml` and populate the `resources` list with the full list of resources you want to target:
```yaml
webhooks:
- name: dragnet.kubemod.io
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    scope: '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
    - configmaps
    - persistentvolumeclaims
    - secrets
    - services
    - daemonsets
    - deployments
    - statefulsets
    - cronjobs
    - jobs
```
2. Run the following:
```bash
kubectl patch mutatingwebhookconfiguration kubemod-mutating-webhook-configuration --patch "$(cat patch.yaml)"
```
