### ISSUE TITLE
Cascading Modrules and not matching selects

### ISSUE THREAD

**Issue by thedatabaseme** [kubemod/kubemod#91]
Hello,

we have the following situation. We want to replace all possible Docker Hub image specifications (like `docker.io/image:tag`, `image:tag`, `docker.io/library/image:tag` ...) in our Pod manifests with our private image registry. We have done some modrules for that like this:

```
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-container-library-and-tag
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all containers, with an image formatted like this: "nginx"
  # and mutate the image to:                                          "myregistry.com/library/nginx:latest" 
  patch:
    - op: replace
      select: '$.spec.containers[?(@.image =~ "^([^./:]+)$")].image'
      path: '/spec/containers/#0/image'
      value: '{{ regexReplaceAll "^([^./:]+)$" .SelectedItem "myregistry.com/library/${1}:latest" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-init-container-library-and-tag
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all initContainers, with an image formatted like this: "nginx"
  # and mutate the image to:                                              "myregistry.com/library/nginx:latest" 
  patch:
    - op: replace
      select: '$.spec.initContainers[?(@.image =~ "^([^.|/]+)(:)(.+)$")].image'
      path: '/spec/initContainers/#0/image'
      value: '{{ regexReplaceAll "^([^.|/]+)(:)(.+)$" .SelectedItem "myregistry.com/library/${1}:${3}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-container-library
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all containers, with an image formatted like this: "nginx:latest"
  # and mutate the image to:                                          "myregistry.com/library/nginx:latest" 
  patch:
    - op: replace
      select: '$.spec.containers[?(@.image =~ "^([^.|/]+)(:)(.+)$")].image'
      path: '/spec/containers/#0/image'
      value: '{{ regexReplaceAll "^([^.|/]+)(:)(.+)$" .SelectedItem "myregistry.com/library/${1}:${3}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-init-container-library
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all initContainers, with an image formatted like this: "nginx:latest"
  # and mutate the image to:                                              "myregistry.com/library/nginx:latest" 
  patch:
    - op: replace
      select: '$.spec.initContainers[?(@.image =~ "^([^.|/]+)(:)(.+)$")].image'
      path: '/spec/initContainers/#0/image'
      value: '{{ regexReplaceAll "^([^.|/]+)(:)(.+)$" .SelectedItem "myregistry.com/library/${1}:${3}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-container
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all containers, with an image formatted like this: "repo/dhcp:latest"
  # and mutate the image to:                                          "myregistry.com/repo/dhcp:latest" 
  patch:
    - op: replace
      select: '$.spec.containers[?(@.image =~ "^([^.]+)(/)(.+)(:)(.+)$")].image'
      path: '/spec/containers/#0/image'
      value: '{{ regexReplaceAll "^([^.]+)(/)(.+)(:)(.+)$" .SelectedItem "myregistry.com/${1}/${3}:${5}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-init-container
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all initContainers, with an image formatted like this: "repo/dhcp:latest"
  # and mutate the image to:                                              "myregistry.com/repo/dhcp:latest" 
  patch:
    - op: replace
      select: '$.spec.initContainers[?(@.image =~ "^([^.]+)(/)(.+)(:)(.+)$")].image'
      path: '/spec/initContainers/#0/image'
      value: '{{ regexReplaceAll "^([^.]+)(/)(.+)(:)(.+)$" .SelectedItem "myregistry.com/${1}/${3}:${5}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-full-container
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all containers, with an image formatted like this: "docker.io/repo/dhcp:latest"
  # and mutate the image to:                                          "myregistry.com/repo/dhcp:latest" 
  patch:
    - op: replace
      select: '$.spec.containers[?(@.image =~ "^(docker.io)(/)(.+)(:)(.+)$")].image'
      path: '/spec/containers/#0/image'
      value: '{{ regexReplaceAll "^(docker.io)(/)(.+)(:)(.+)$" .SelectedItem "myregistry.com/${3}:${5}" }}'
---
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-io-full-init-container
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'
  # this will find all initContainers, with an image formatted like this: "docker.io/repo/dhcp:latest"
  # and mutate the image to:                                              "myregistry.com/repo/dhcp:latest" 
  patch:
    - op: replace
      select: '$.spec.initContainers[?(@.image =~ "^(docker.io)(/)(.+)(:)(.+)$")].image'
      path: '/spec/initContainers/#0/image'
      value: '{{ regexReplaceAll "^(docker.io)(/)(.+)(:)(.+)$" .SelectedItem "myregistry.com/${3}:${5}" }}'
```

Because we need regcreds for the private registry, we then created a second mutation rule, that adds the regcred secret as `imagePullSecret`.

```
apiVersion: api.kubemod.io/v1beta1
kind: ModRule
metadata:
  name: docker-remote-jfrog-io-image-pull-secrets
  namespace: kubemod-system
spec:
  type: Patch
  targetNamespaceRegex: .*
  match:
    - select: '$.kind'
      matchValue: 'Pod'

    - select: '$.spec.containers[*].image'
      matchRegex: '^myregistry\.com/.*$'

    - select: '$.spec.imagePullSecrets[*].name'
      matchValue: 'regcred'
      negate: true

  patch:
    - op: add
      path: '/spec/imagePullSecrets/-1'
      value: |-
        name: regcred
```

For testing we use this deployment for example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mytest
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: initnginx
        image: docker.io/nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      containers:
      - name: nginx
        image: docker.io/library/nginx:1.14.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: nginxtest
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
```

What we now experience is the following.

- The replacement of the `image` reference in the Pod work as expected. This applies for all combinations and for all containers and initContainers.
- The rule for adding the `regcred` as `imagePullSecret` does not match and is not triggered.

We found out, that all rules seem to check always the initial `Pod` specification. Cause if we change `matchRegex: '^myregistry\.com/.*$'` to `matchRegex: '^docker.io/.*$'`, the rule is triggered and does what it should. This makes me a bit confused cause I assumed, that changing the `image` specification of a Pod will lead to a status update which will lead to the regcred rule to get triggered. We worked around this issue by removing the `select` part in the regcred rule entirely. This now adds regcreds to all Pods regardless if needed or not.

So I have the following questions or proposals:

1. Is my understanding correct, that all rules will check the initial resource specification and not getting triggered after mutation by another rule happened?
2. If so, would this not be a reasonable feature to have something like cascading rules? For example. Kubemod is getting triggered and checks the resource if a modrule needs to be applied, then a second modrule will get triggered and the already mutated resource will be checked by this rule and so on. After all cascading rules are finished, the final mutated resource definition is handed back to Kubernetes and gets applied. I know that you don't have an influence in the order when admission webhooks will be called, but this will be "inside" Kubemod in my understanding and therefore "self-contained".
3. Do you have any idea how this specific issue could be solved otherwise?

I hope my explanation is comprehensible. If you have any questions, don't hesitate to ask.

Kind regards
Philip
